# Generated by Django 3.2 on 2021-05-20 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
